/*
 * Emilie Bourg / Lucile Berger / Pauline Cantie
 * TDC
 * 28/11/2023
 */
package threes_jeu;

import java.awt.Color;
import java.awt.Font;
import java.awt.GridLayout;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author Emilie
 */
public class FenetrePrincipale extends javax.swing.JFrame {

    Grille grille;

    /**
     * Creates new form FenetrePrincipale
     */
    public FenetrePrincipale() {
        initComponents();
        setTitle("Bienvenue dans le jeu Threes!");
        créer_grille(4, 80, 80);
        System.out.println(grille);
        setLocationRelativeTo(null);
        setSize(800, 500);

        addKeyListener(new KeyAdapter() {
            @Override
            public void keyPressed(KeyEvent e) {
                if (e.getKeyCode() == KeyEvent.VK_UP) {
                    hautActionPerformed(null);
                } else if (e.getKeyCode() == KeyEvent.VK_LEFT) {
                    gaucheActionPerformed(null);
                } else if (e.getKeyCode() == KeyEvent.VK_RIGHT) {
                    droiteActionPerformed(null);
                } else if (e.getKeyCode() == KeyEvent.VK_DOWN) {
                    basActionPerformed(null);
                }
            }
        });
        setFocusable(true);
        setFocusTraversalKeysEnabled(false);

    }

    /**
     * Permet la création de la grille dans la fenetre
     *
     * @param nb_case par lignes et colonnes
     * @param taille_grille
     * @param taille_cellule
     */
    public void créer_grille(int nb_case, int taille_grille, int taille_cellule) {
        int nbLignes = nb_case;
        int nbColonnes = nb_case;
        getContentPane().add(endroitgrille, new org.netbeans.lib.awtextra.AbsoluteConstraints(taille_grille, taille_grille, nbColonnes * taille_cellule, nbLignes * taille_cellule));
        this.pack();
        this.revalidate();
        grille = new Grille(nbLignes, nbColonnes);
        endroitgrille.setLayout(new GridLayout(nbLignes, nbColonnes));

        for (int i = 0; i < nbLignes; i++) {
            for (int j = 0; j < nbColonnes; j++) {
                endroitgrille.add(grille.grillecellule[i][j]);
            }
        }
    }

    public void fleches() {
        String message
                = "<html><body style='width: 300px; padding: 10px;'>"
                + "<h1 style='color: #1E90FF; font-style: italic;'>Utilisez les flèches sur l'interface graphique ou sur le clavier pour jouer.</h1>"
                + "</body></html>";

        JOptionPane.showMessageDialog(this,
                message,
                "Utilisation des flèches",
                JOptionPane.INFORMATION_MESSAGE);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        endroitgrille = new javax.swing.JPanel();
        haut = new javax.swing.JButton();
        bas = new javax.swing.JButton();
        droite = new javax.swing.JButton();
        gauche = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        endroitgrille.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout endroitgrilleLayout = new javax.swing.GroupLayout(endroitgrille);
        endroitgrille.setLayout(endroitgrilleLayout);
        endroitgrilleLayout.setHorizontalGroup(
            endroitgrilleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        endroitgrilleLayout.setVerticalGroup(
            endroitgrilleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        getContentPane().add(endroitgrille, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 270, 140));

        haut.setBackground(new java.awt.Color(204, 204, 255));
        haut.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        haut.setText("↑");
        haut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hautActionPerformed(evt);
            }
        });
        getContentPane().add(haut, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 70, 50, 50));

        bas.setBackground(new java.awt.Color(204, 204, 255));
        bas.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        bas.setText("↓ ");
        bas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                basActionPerformed(evt);
            }
        });
        getContentPane().add(bas, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 170, 50, 50));

        droite.setBackground(new java.awt.Color(204, 204, 255));
        droite.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        droite.setText("→");
        droite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                droiteActionPerformed(evt);
            }
        });
        getContentPane().add(droite, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 120, 50, 50));

        gauche.setBackground(new java.awt.Color(204, 204, 255));
        gauche.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        gauche.setText("←");
        gauche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gaucheActionPerformed(evt);
            }
        });
        getContentPane().add(gauche, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 120, 50, 50));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 230, -1, -1));

        jButton1.setText("utilisation des flèches ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 340, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void hautActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hautActionPerformed
        fin_jeu();
        grille.deplacementHaut();
        System.out.println(grille);
        endroitgrille.repaint();
    }//GEN-LAST:event_hautActionPerformed

    private void gaucheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gaucheActionPerformed
        fin_jeu();
        grille.deplacementGauche();
        System.out.println(grille);
        endroitgrille.repaint();
    }//GEN-LAST:event_gaucheActionPerformed

    private void droiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_droiteActionPerformed
        fin_jeu();
        grille.deplacementDroite();
        System.out.println(grille);
        endroitgrille.repaint();
    }//GEN-LAST:event_droiteActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.fleches();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void basActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_basActionPerformed
        fin_jeu();
        grille.deplacementBas();
        System.out.println(grille);
        endroitgrille.repaint();
    }//GEN-LAST:event_basActionPerformed

    public void fin_jeu() {
        if (grille.possible_deplaGauche() == false && grille.possible_deplaDroite() == false && grille.possible_deplaHaut() == false && grille.possible_deplaBas() == false) {
            int score;
            score = grille.compte_score();
            this.dispose();
            new FenetreFin(score).setVisible(true);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FenetrePrincipale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FenetrePrincipale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FenetrePrincipale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FenetrePrincipale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FenetrePrincipale().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bas;
    private javax.swing.JButton droite;
    private javax.swing.JPanel endroitgrille;
    private javax.swing.JButton gauche;
    private javax.swing.JButton haut;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
